// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/subscriptions": {
            "get": {
                "description": "Lists subscription records",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "List subscription records",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.SubscriptionResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Creates new subscription record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Create new subscription record",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.SubscriptionResponse"
                        }
                    }
                }
            }
        },
        "/subscriptions/total-cost": {
            "get": {
                "description": "Calculating subscription cost based on filtering parametres",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Calculate subscriptin cost",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date of period (MM-YYYY)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date of period (MM-YYYY)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Service name for filtering",
                        "name": "service_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "User UUID for filtering",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SubscriptionCostResponse"
                        }
                    }
                }
            }
        },
        "/subscriptions/{id}": {
            "get": {
                "description": "Gets subscription record by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Get subscription record by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Subscription ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SubscriptionResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Makes full update of subscription recored by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Update subscription recored by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Subscription ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New data for subscription record",
                        "name": "subscription",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SubscriptionResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes subscription record by ID",
                "tags": [
                    "subscriptions"
                ],
                "summary": "Delete subscription record by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Subscription ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No content"
                    }
                }
            },
            "patch": {
                "description": "Makes partial update of subscription record by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Patch subscription record by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Subscription ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Data for partial updating subscription record",
                        "name": "subscription",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SubscriptionResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.SubscriptionCostResponse": {
            "description": "Response with total cost of subscription records",
            "type": "object",
            "properties": {
                "cost": {
                    "description": "@Description Integer total cost of subscription records\n@Exmaple 2344",
                    "type": "integer"
                }
            }
        },
        "models.SubscriptionRequest": {
            "description": "Request to create or update subscription record",
            "type": "object",
            "properties": {
                "end_date": {
                    "description": "@Description Month and year of subsription end, format: MM-YYYY\n@Example 08-2025",
                    "type": "string"
                },
                "price": {
                    "description": "@Description Subscription price (integer number of rubles)\n@Exmaple 399",
                    "type": "integer"
                },
                "service_name": {
                    "description": "@Description Service Name\n@Example Yandex Plus",
                    "type": "string"
                },
                "start_date": {
                    "description": "@Description Month and year of subscription srart, format: MM-YYYY\n@Example 07-2025",
                    "type": "string"
                },
                "user_id": {
                    "description": "@Description User's UUID\n@Example 60601fee-2bf1-4721-ae6f-7636e79a0cba",
                    "type": "string"
                }
            }
        },
        "models.SubscriptionResponse": {
            "description": "Response with information about subscription",
            "type": "object",
            "properties": {
                "end_date": {
                    "description": "@Description Month and year of subsription end, format: MM-YYYY\n@Example 08-2025",
                    "type": "string"
                },
                "id": {
                    "description": "@Description Integer ID of subscription record\n@Example 1",
                    "type": "integer"
                },
                "price": {
                    "description": "@Description Subscription price (integer number of rubles)\n@Exmaple 399",
                    "type": "integer"
                },
                "service_name": {
                    "description": "@Description Service Name\n@Example Yandex Plus",
                    "type": "string"
                },
                "start_date": {
                    "description": "@Description Month and year of subscription srart, format: MM-YYYY\n@Example 07-2025",
                    "type": "string"
                },
                "user_id": {
                    "description": "@Description User's UUID\n@Example 60601fee-2bf1-4721-ae6f-7636e79a0cba",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Effective-Mobile-Test API",
	Description:      "REST API для агрегации данных об онлайн подписках пользователей",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
